pre-release version ok...go to sleep

diff --git a/gg-select b/gg-select
--- a/gg-select
+++ b/gg-select
@@ -32,21 +32,22 @@ if [ $# == 0 ];then
 	    git status
 	    exit 1
 	fi
-
+	git checkout $currentBranch
 	printf "Do you what to select the latest version soft in the $master branch like this?\n"
 	gggttt;echo "git merge --no-ff $master"
-	gggttt;echo "tag inUse-$currentTagName -a -m ""fork $master into baseOn, version $currentTagName$"""
+	gggttt;echo "tag inUse-$currentTagName -a -m \"fork $master into baseOn, version $currentTagName\""
 	read temp
-	git checkout $currentBranch
-	git merge --no-ff $master
-	git tag inUse-$currentTagName -a -m "fork $master into baseOn, version $currentTagName$"
-elif [ $# == 1 ]
 	
-	git checkout $1 \
-		|| printf "error go to $#\n check your spell\n We can go to \n" \
-		&& git branch \
-		&& git tag \
-		&& exit 1
+	git merge --no-ff $master -m "fork $master into baseOn, version $currentTagName"
+	git tag inUse-$currentTagName -a -m "fork $master into baseOn, version $currentTagName"
+elif [ $# == 1 ];then
+	git checkout $1 >/dev/null
+	if [ $? != 0 ]; then
+		printf "error go to $#\n check your spell\n We can go to \n"
+		git branch
+		git tag
+		exit 1
+	fi
 
 	get_currentTagName
 	if [ -z $currentTagName ]; then
@@ -54,13 +55,14 @@ elif [ $# == 1 ]
 	    git status
 	    exit 1
 	fi
+	git checkout $currentBranch
 	printf "Do you what to select the latest version soft in the $1 branch like this?\n"
 	gggttt;echo "git merge --no-ff $1"
-	gggttt;echo "git tag inUse-$currentTagName -a -m ""fork $1 into baseOn, version $currentTagName$"""
+	gggttt;echo "git tag inUse-$currentTagName -a -m \"fork $1 into baseOn, version $currentTagName\""
 
 	read temp
-	git checkout $currentBranch
-	git merge --no-ff $1
+	
+	git merge --no-ff $1 -m "fork $master into baseOn, version $currentTagName"
 	git tag inUse-$currentTagName -a -m "fork $1 into baseOn, version $currentTagName$"
 else
 	printf "error parameter numbers!!\n"
diff --git a/gg-work-init b/gg-work-init
--- a/gg-work-init
+++ b/gg-work-init
@@ -31,26 +31,30 @@ if [ -z currentTagName ]; then
 fi
 
 printf 'do you what to git init the directory like this?\n'
-cp $installPath/gg-pre-commit .git/hooks/pre-commit\
-	|| printf "please go to the git root to cp the pre-commit\n"\
-	&& exit 1
+if [ -e .git/hooks/pre-commit ];then
+	echo
+else
+	cp $installPath/gg-pre-commit .git/hooks/pre-commit
+	printf "please go to the git root to cp the pre-commit\n"
+	exit 1
+fi
 
 get_basedOn
-if [ $# == 0 ];then
+if [ $# == 0 ]; then
 	gggttt;echo "git checkout -b $basedOn"
+	gggttt;echo "git tag inUse-$currentTagName -a -m \"init $master into baseOn, version $currentTagName\""
 	read temp
 	git checkout -b $basedOn
-	git tag inUse-$currentTagName -a -m "init $master into baseOn, version $currentTagName$"
-elif [ $# == 1 ]
-	printf "\tgit checkout $1\n"
-	gggttt;echo "git checkout -b $basedOn"
+	git tag inUse-$currentTagName -a -m "init $master into baseOn, version $currentTagName"
+elif [ $# == 1 ]; then
 	
-	read temp
-	git checkout $1 \
-		|| echo "error go to $1, check your spell, We can go to \n" \
-		&& git branch \
-		&& git tag \
-		&& exit 1
+	git checkout $1 > /dev/null
+	if [ $? != 0 ];then
+		echo "error go to $1, check your spell, We can go to \n"
+		git branch
+		git tag
+		exit 1
+	fi
 	get_currentTagName
 	if [ -z $currentTagName ]; then
 	    echo "$1 don't have a tag name, you should give one to it"
@@ -58,13 +62,13 @@ elif [ $# == 1 ]
 	    exit 1
 	fi
 
+	gggttt;echo "git checkout -b $basedOn"
+	gggttt;echo "git tag inUse-$currentTagName -a -m \"init $1 into baseOn, version $currentTagName\""
+	read temp
 	git checkout -b $basedOn
-	git tag inUse-$currentTagName -a -m "init $master into baseOn, version $currentTagName$"
+	git tag inUse-$currentTagName -a -m "init $1 into baseOn, version $currentTagName"
 else
 	printf "error parameter numbers!!\n"
 	exit 1
 fi
-
-read temp
-
 
diff --git a/gg-work-update b/gg-work-update
--- a/gg-work-update
+++ b/gg-work-update
@@ -25,36 +25,39 @@ if [ $currentBranchType != 'work' ]; then
 	exit 1
 fi
 
-get_work_basedOn
+get_basedOn
+echo $work_basedOn
 if [ $# == 0 ];then
-	git checkout $work_basedOn
+	git checkout $basedOn
 	get_currentTagName
 	get_currentTagVersion
 	git checkout $thisWorkBranch
 
 	printf "Do you want to update your work branch like this?\n"
-	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/$work_basedOn-$currentTagVersion"
-	gggttt;echo "git merge --no-ff $currentTagName"
+	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion"
+	gggttt;echo "git merge --no-ff $currentTagName -m \"update $thisWorkBranch with $currentTagName\"" 
 
 	read temp
-	git checkout -b $thisWorkBranchTypeAll/$work_basedOn-$currentTagVersion
-	git merge --no-ff $currentTagName
+	git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion
+	git merge --no-ff $currentTagName -m "update $thisWorkBranch with $currentTagName"
 	
-elif [ $# == 1 ]
-	git checkout $1 \
-		|| printf "error go to $#\n check your spell\n We can go to \n" \
-		&& git branch \
-		&& git tag \
-		&& exit 1
+elif [ $# == 1 ]; then
+	git checkout $1 > /dev/null
+	if [ $? != 0 ];then
+		printf "error go to $#\n check your spell\n We can go to \n"
+		git branch
+		git tag
+		exit 1
+	fi
 	get_currentTagName
 	get_currentTagVersion
 	printf "Do you want to update your work branch like this?\n"
-	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/$work_basedOn-$currentTagVersion"
-	gggttt;echo "git merge --no-ff $currentTagName"
+	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion"
+	gggttt;echo "git merge --no-ff $currentTagName -m \"update $thisWorkBranch with $currentTagName\""
 
 	read temp
-	git checkout -b $thisWorkBranchTypeAll/$work_basedOn-$currentTagVersion
-	git merge --no-ff $currentTagName
+	git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion
+	git merge --no-ff $currentTagName -m "update $thisWorkBranch with $currentTagName"
 
 else
 	printf "error parameter numbers!!\n"
