many bugs fixed

diff --git a/gg-work-init-with b/gg-work-init-with
--- a/gg-work-init-with
+++ b/gg-work-init-with
@@ -40,9 +40,23 @@ else
 fi
 
 get_basedOn
-if [ $# == 0 ]; then
+if [ $# == 1 ]; then
+	git checkout $1 > /dev/null
+	if [ $? != 0 ];then
+		echo "error go to $1, check your spell, We can go to \n"
+		git branch
+		git tag
+		exit 1
+	fi
+	get_currentTagName
+	if [ -z $currentTagName ]; then
+	    echo "$1 don't have a tag name, you should give one to it"
+	    git status
+	    exit 1
+	fi
+
 	gggttt;echo "gg-open-branch-without-history $basedOn"
-	gggttt;echo "git tag inUse-$currentTagName -a -m \"init $master into baseOn, version $currentTagName\""
+	gggttt;echo "git tag inUse-$currentTagName -a -m \"init $1 into baseOn, version $currentTagName\""
 	read temp
 	gg-open-branch-without-history $basedOn
 	git add .
diff --git a/gg-work-update-with b/gg-work-update-with
--- a/gg-work-update-with
+++ b/gg-work-update-with
@@ -27,15 +27,20 @@ fi
 
 get_basedOn
 echo $work_basedOn
-if [ $# == 0 ];then
-	git checkout $basedOn
+
+if [ $# == 1 ]; then
+	git checkout $1 > /dev/null
+	if [ $? != 0 ];then
+		printf "error go to $#\n check your spell\n We can go to \n"
+		git branch
+		git tag
+		exit 1
+	fi
 	get_currentTagName
 	get_currentTagVersion
-	git checkout $thisWorkBranch
-
 	printf "Do you want to update your work branch like this?\n"
 	gggttt;echo "git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion"
-	gggttt;echo "git merge --no-ff $currentTagName -m \"update $thisWorkBranch with $currentTagName\"" 
+	gggttt;echo "git merge --no-ff $currentTagName -m \"update $thisWorkBranch with $currentTagName\""
 
 	read temp
 	git checkout -b $thisWorkBranchTypeAll/basedOn-$currentTagVersion
